-- MySQL Script generated by MySQL Workbench
-- Sun Aug 26 15:20:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema novinhasrvdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema novinhasrvdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `novinhasrvdb` DEFAULT CHARACTER SET utf8 ;
USE `novinhasrvdb` ;

-- -----------------------------------------------------
-- Table `novinhasrvdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novinhasrvdb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `prefSexo` TINYINT NOT NULL,
  `prefEsporte` TINYINT NOT NULL,
  `prefReligioso` TINYINT NOT NULL,
  `prefMusica` TINYINT NOT NULL,
  `prefGames` TINYINT NOT NULL,
  `prefIdade` TINYINT NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
